apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: knowengress
  namespace: default
spec:
  tls:
  - hosts:
    - SERVER_DNS_NAME
    secretName: knowssl-secret
  rules:
  - host: SERVER_DNS_NAME
    http:
      paths:
      - backend:
          serviceName: support-nginx-ingress-default-backend
          servicePort: 80
        path: /
