kind: ServiceAccount
apiVersion: v1
metadata:
  name: nest
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-submission
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete", "update"]
---
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nest-job-submission
subjects:
 - kind: ServiceAccount
   name: nest
   namespace: default
roleRef:
   kind: ClusterRole
   name: job-submission
   apiGroup: rbac.authorization.k8s.io
